linters:
  enable:
    - goconst
    - gofmt
    - govet
    - staticcheck
    - typecheck
    - unused
  fast:
    enable-all: false
    allow-parallel-tests: true

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true