// Code generated by ConfigForge. DO NOT EDIT.
//
// Source: manifests/*.yaml

package config

import "time"

// EnvMetadataEntry describes an environment variable declared by manifests.
type EnvMetadataEntry struct {
	Option    string
	Component string
	Type      string
}

// generatedDuration parses a Go duration string on init for generated defaults.
func generatedDuration(d string) time.Duration {
	parsed, _ := time.ParseDuration(d)
	return parsed
}

// EnvMetadata maps ConfigForge environment variables to metadata.
var EnvMetadata = map[string]EnvMetadataEntry{
	"CONFIGFORGE_DEFAULT_RATE_LIMIT_REQUESTS": {Option: "requests", Component: "route-security", Type: "integer"},
	"CONFIGFORGE_DEFAULT_RATE_LIMIT_WINDOW":   {Option: "window", Component: "route-security", Type: "duration"},
	"CONFIGFORGE_REDACT_HEADERS":              {Option: "redact_headers", Component: "privacy", Type: "string_array"},
	"CONFIGFORGE_REDACT_QUERY_PARAMETERS":     {Option: "redact_query_parameters", Component: "privacy", Type: "string_array"},
}

// ManifestDefaults returns the default values declared in manifests,
// keyed by "component.option".
var ManifestDefaults = map[string]any{
	"feature-flags.rollout_percentage": 0,
	"privacy.redact_headers":           []string{"authorization", "cookie", "x-api-key"},
	"privacy.redact_query_parameters":  []string{"password", "token", "api_key"},
	"route-security.requests":          100,
	"route-security.window":            generatedDuration("1m"),
}
