// Package generator produces deterministic generated artifacts from manifests:
//
//   - Go source with default values and environment-variable metadata
//   - Markdown documentation for each manifest
//
// Generated files include the standard ConfigForge "DO NOT EDIT" comment.
package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/ADITYA-CODE-SOURCE/configforge/internal/manifest"
)

const generatedHeader = `// Code generated by ConfigForge. DO NOT EDIT.
//
// Source: manifests/*.yaml

package config

import "time"

// EnvMetadataEntry describes an environment variable declared by manifests.
type EnvMetadataEntry struct {
	Option    string
	Component string
	Type      string
}

// generatedDuration parses a Go duration string on init for generated defaults.
func generatedDuration(d string) time.Duration {
	parsed, _ := time.ParseDuration(d)
	return parsed
}

`

// GenerateDefaults returns deterministic Go source code that exposes the
// manifest-declared default values and environment-variable metadata.
func GenerateDefaults(manifests []manifest.Manifest) []byte {
	var b bytes.Buffer
	b.WriteString(generatedHeader)

	envEntries := collectEnvMetadata(manifests)
	if len(envEntries) > 0 {
		b.WriteString("// EnvMetadata maps ConfigForge environment variables to metadata.\n")
		b.WriteString("var EnvMetadata = map[string]EnvMetadataEntry{\n")
		for _, entry := range envEntries {
			fmt.Fprintf(&b, "\t%q: {Option: %q, Component: %q, Type: %q},\n",
				entry.Env, entry.Option, entry.Component, entry.Type)
		}
		b.WriteString("}\n\n")
	}

	b.WriteString("// ManifestDefaults returns the default values declared in manifests,\n")
	b.WriteString("// keyed by \"component.option\".\n")
	b.WriteString("var ManifestDefaults = map[string]any{\n")
	for _, m := range sortsManifests(manifests) {
		optionNames := sortedOptionNames(m.Options)
		for _, name := range optionNames {
			option := m.Options[name]
			key := m.Name + "." + name
			fmt.Fprintf(&b, "\t%q: %s,\n", key, formatDefault(option.Type, option.Default))
		}
	}
	b.WriteString("}\n")

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		// If gofmt fails, return the unformatted source to avoid hiding bugs.
		return b.Bytes()
	}
	return formatted
}

func collectEnvMetadata(manifests []manifest.Manifest) []envEntry {
	var entries []envEntry
	for _, m := range sortsManifests(manifests) {
		for _, name := range sortedOptionNames(m.Options) {
			option := m.Options[name]
			if option.Env == "" {
				continue
			}
			entries = append(entries, envEntry{
				Env:       option.Env,
				Option:    name,
				Component: m.Name,
				Type:      option.Type,
			})
		}
	}
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Env < entries[j].Env
	})
	return entries
}

type envEntry struct {
	Env       string
	Option    string
	Component string
	Type      string
}

// GenerateDocs returns deterministic Markdown documentation for the supplied
// manifests.
func GenerateDocs(manifests []manifest.Manifest) []byte {
	var b bytes.Buffer
	b.WriteString("# Configuration Options\n\n")
	b.WriteString("Options are declared in manifests under `manifests/` and are generated deterministically by ConfigForge.\n\n")

	for _, m := range sortsManifests(manifests) {
		fmt.Fprintf(&b, "## %s\n\n%s\n\n", m.Name, m.Description)
		b.WriteString("| Option | Type | Default | Env | Description |\n")
		b.WriteString("| --- | --- | --- | --- | --- |\n")
		for _, name := range sortedOptionNames(m.Options) {
			option := m.Options[name]
			env := option.Env
			if env == "" {
				env = "—"
			}
			fmt.Fprintf(&b, "| `%s` | `%s` | `%s` | `%s` | %s |\n",
				name, option.Type, formatDefaultMarkdown(option.Type, option.Default), env, option.Description)
		}
		b.WriteString("\n")
	}
	return b.Bytes()
}

func sortsManifests(manifests []manifest.Manifest) []manifest.Manifest {
	out := append([]manifest.Manifest(nil), manifests...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func sortedOptionNames(opts map[string]manifest.Option) []string {
	names := make([]string, 0, len(opts))
	for n := range opts {
		names = append(names, n)
	}
	sort.Strings(names)
	return names
}

func formatDefault(typeName string, defaultVal any) string {
	switch typeName {
	case "string":
		return fmt.Sprintf("%q", asString(defaultVal))
	case "integer":
		return fmt.Sprintf("%d", asInt(defaultVal))
	case "duration":
		return fmt.Sprintf("generatedDuration(%q)", asString(defaultVal))
	case "boolean":
		if b, ok := defaultVal.(bool); ok && b {
			return "true"
		}
		return "false"
	case "string_array":
		return formatStringArrayGo(defaultVal)
	default:
		return fmt.Sprintf("%v", defaultVal)
	}
}

func formatDefaultMarkdown(typeName string, defaultVal any) string {
	switch typeName {
	case "string_array":
		return formatStringArrayMarkdown(defaultVal)
	default:
		return strings.TrimSpace(fmt.Sprintf("%v", defaultVal))
	}
}

func formatStringArrayGo(defaultVal any) string {
	items, ok := defaultVal.([]any)
	if !ok {
		return "nil"
	}
	var parts []string
	for _, item := range items {
		parts = append(parts, fmt.Sprintf("%q", asString(item)))
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func formatStringArrayMarkdown(defaultVal any) string {
	items, ok := defaultVal.([]any)
	if !ok {
		return "—"
	}
	var parts []string
	for _, item := range items {
		parts = append(parts, asString(item))
	}
	return strings.Join(parts, ", ")
}

func asString(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	return fmt.Sprintf("%v", v)
}

func asInt(v any) int {
	switch n := v.(type) {
	case int:
		return n
	case int64:
		return int(n)
	case float64:
		return int(n)
	}
	return 0
}
