package generator

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/ADITYA-CODE-SOURCE/configforge/internal/manifest"
)

func TestGenerateDeterministic(t *testing.T) {
	manifests, err := manifest.LoadDir(filepath.Join("..", "..", "manifests"))
	if err != nil {
		t.Fatalf("LoadDir: %v", err)
	}

	first := GenerateDefaults(manifests)
	second := GenerateDefaults(manifests)
	if !bytes.Equal(first, second) {
		t.Fatal("GenerateDefaults is not deterministic")
	}

	docsFirst := GenerateDocs(manifests)
	docsSecond := GenerateDocs(manifests)
	if !bytes.Equal(docsFirst, docsSecond) {
		t.Fatal("GenerateDocs is not deterministic")
	}
}

func TestGenerateGoldenDefaults(t *testing.T) {
	manifests, err := manifest.LoadDir(filepath.Join("..", "..", "manifests"))
	if err != nil {
		t.Fatalf("LoadDir: %v", err)
	}

	got := GenerateDefaults(manifests)
	goldenPath := filepath.Join("..", "..", "pkg", "config", "generated.go")
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("generated defaults does not match golden file %s", goldenPath)
	}
}

func TestGenerateGoldenDocs(t *testing.T) {
	manifests, err := manifest.LoadDir(filepath.Join("..", "..", "manifests"))
	if err != nil {
		t.Fatalf("LoadDir: %v", err)
	}

	got := GenerateDocs(manifests)
	goldenPath := filepath.Join("..", "..", "docs", "configuration_options.md")
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("generated docs does not match golden file %s", goldenPath)
	}
}

func TestGeneratedGoCompiles(t *testing.T) {
	manifests, err := manifest.LoadDir(filepath.Join("..", "..", "manifests"))
	if err != nil {
		t.Fatalf("LoadDir: %v", err)
	}

	got := GenerateDefaults(manifests)
	if !bytes.Contains(got, []byte("Code generated by ConfigForge. DO NOT EDIT.")) {
		t.Fatal("missing DO NOT EDIT header")
	}
	if !bytes.Contains(got, []byte(`var EnvMetadata`)) {
		t.Fatal("missing EnvMetadata variable")
	}
	if !bytes.Contains(got, []byte(`var ManifestDefaults`)) {
		t.Fatal("missing ManifestDefaults variable")
	}
}
